### ISSUE TITLE
KeyError due to UAV_NAME

### ISSUE THREAD

**Issue by Larsdb98** [ctu-mrs/color_picker#1]
Hello, when trying to run a couple of launchfiles (including gui.launch), this node crashes and the following Python error shows up:

```bash
PluginManager._load_plugin() could not load plugin "balloon_color_picker/Color Picker Plugin":
Traceback (most recent call last):
  File "/opt/ros/noetic/lib/python3/dist-packages/qt_gui/plugin_handler.py", line 102, in load
    self._load()
  File "/opt/ros/noetic/lib/python3/dist-packages/qt_gui/plugin_handler_direct.py", line 55, in _load
    self._plugin = self._plugin_provider.load(self._instance_id.plugin_id, self._context)
  File "/opt/ros/noetic/lib/python3/dist-packages/qt_gui/composite_plugin_provider.py", line 72, in load
    instance = plugin_provider.load(plugin_id, plugin_context)
  File "/opt/ros/noetic/lib/python3/dist-packages/qt_gui/composite_plugin_provider.py", line 72, in load
    instance = plugin_provider.load(plugin_id, plugin_context)
  File "/opt/ros/noetic/lib/python3/dist-packages/rqt_gui_py/ros_py_plugin_provider.py", line 61, in load
    return super(RosPyPluginProvider, self).load(plugin_id, plugin_context)
  File "/opt/ros/noetic/lib/python3/dist-packages/qt_gui/composite_plugin_provider.py", line 72, in load
    instance = plugin_provider.load(plugin_id, plugin_context)
  File "/opt/ros/noetic/lib/python3/dist-packages/rqt_gui/ros_plugin_provider.py", line 106, in load
    return class_ref(plugin_context)
  File "/root/moma_ws/src/mapping_pipeline_packages/color_picker/src/balloon_color_picker/plugin_module.py", line 79, in __init__
    new_wdg = MyWidget.MyWidget()
  File "/root/moma_ws/src/mapping_pipeline_packages/color_picker/src/balloon_color_picker/MyWidget.py", line 110, in __init__
    self.uav_name = os.environ['UAV_NAME']
  File "/usr/lib/python3.8/os.py", line 675, in __getitem__
    raise KeyError(key) from None
KeyError: 'UAV_NAME'

[uav/balloon_color_picker_gui-3] process has died [pid 150250, exit code 1, cmd /root/moma_ws/src/mapping_pipeline_packages/color_picker/scripts/plugin.py __name:=balloon_color_picker_gui __log:=/root/.ros/log/32a03072-9807-11ee-999a-8cf8c5004c27/uav-balloon_color_picker_gui-3.log].
log file: /root/.ros/log/32a03072-9807-11ee-999a-8cf8c5004c27/uav-balloon_color_picker_gui-3*.log
```

This error persists even with the launch command lines you have provided in the README.

I ran this on a ROS Noetic environment (Ubuntu 20.04).

I need this package in order to figure out the right detection parameters in order to use your  "object_detect" ROS package to detect certain items from an image stream.

**Comment by Larsdb98** [comment]
I managed to fix it, I believe this issue stemmed from running this package inside a docker with missing dependencies.
